//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cta_vuelo
    {
        public cta_vuelo()
        {
            this.cta_pasajero = new HashSet<cta_pasajero>();
        }
    
        public decimal cons_vuelo { get; set; }
        public string nombre { get; set; }
        public string avion_numero_serie { get; set; }
    
        public virtual cta_avion cta_avion { get; set; }
        public virtual ICollection<cta_pasajero> cta_pasajero { get; set; }
    }
}
