//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cta_pasajero
    {
        public cta_pasajero()
        {
            this.cta_vuelo = new HashSet<cta_vuelo>();
        }
    
        public decimal cons_pasajero { get; set; }
        public string tipo_documento { get; set; }
        public string documento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
    
        public virtual ICollection<cta_vuelo> cta_vuelo { get; set; }
    }
}
