//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cta_avion
    {
        public cta_avion()
        {
            this.cta_vuelo = new HashSet<cta_vuelo>();
        }
    
        public string numero_serie { get; set; }
        public string nombre { get; set; }
        public decimal cons_aerolinea { get; set; }
    
        public virtual cta_aerolinea cta_aerolinea { get; set; }
        public virtual ICollection<cta_vuelo> cta_vuelo { get; set; }
    }
}
