//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cta_aerolinea
    {
        public cta_aerolinea()
        {
            this.cta_avion = new HashSet<cta_avion>();
        }
    
        public decimal cons_aerolinea { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<cta_avion> cta_avion { get; set; }
    }
}
