//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportModelContext : DbContext
    {
        public AirportModelContext()
            : base("name=AirportModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cta_aerolinea> cta_aerolinea { get; set; }
        public DbSet<cta_avion> cta_avion { get; set; }
        public DbSet<cta_pasajero> cta_pasajero { get; set; }
        public DbSet<cta_vuelo> cta_vuelo { get; set; }
    }
}
